services:
  - type: web
    name: device-remote-websocket
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: device-remote-websocket
          property: port